
## these sensitivity tests apply only to residential electricity heating technologies, which are: 
# RES-DD-ELC-HPSH-S_HEAT
# RES-JD-ELC-HPSH-S_HEAT
# RES-DD-ELC-HEATR-S_HEAT
# RES-JD-ELC-HEATR-S_HEAT
# the wildcard becomes RES*ELC*S_HEAT

# NOTE that we currently set base year AFAs of 0.08. We need to TFM_Update this to 1 if we're not modifying it directly (so it doesn't clash with other things) 


# AF 80% 

WorkBookName = "SuppXLS/Scen_Sensitivity_RESAF_08" 

[Residential_AF_Sensitivity_08]
Description = "Sets AF for res techs to 0.8 (with timeslice inheritance)."
SheetName = "ResidentialAFSensitivity"
TagName = "TFM_INS"
DataLocation = "data_raw/coded_assumptions/sensitivities/af_testing/res_af_08.csv"

[Residential_Reset_AFA_for_single_AF]
Description = "Resets AFA to default after baseyear."
SheetName = "ResidentialAFSensitivity"
TagName = "TFM_INS"
DataLocation = "data_raw/coded_assumptions/sensitivities/af_testing/reset_afa_default.csv"

# AFA 80% 

[Residential_AFA_Sensitivity_08]
WorkBookName = "SuppXLS/Scen_Sensitivity_RESAFA_08" 
Description = "Sets AFA for res techs to 0.8 (with timeslice inheritance)."
SheetName = "ResidentialAFASensitivity"
TagName = "TFM_INS"
DataLocation = "data_raw/coded_assumptions/sensitivities/af_testing/res_afa_08.csv"

# AF per slice 


[Residential_AF_Slice_Sensitivity]
WorkBookName = "SuppXLS/Scen_Sensitivity_RESAF_perslice" 
Description = "Sets Timeslice specific AFs for residential tests"
SheetName = "ResidentialAFSliceSensitivity"
TagName = "TFM_INS"
DataLocation = "data_raw/coded_assumptions/sensitivities/af_testing/res_af_per_slice_08.csv"

[Residential_Reset_AFA_for_TS_AF]
WorkBookName = "SuppXLS/Scen_Sensitivity_RESAF_perslice" 
Description = "Resets AFA to default after baseyear (for TS AF testing)"
SheetName = "ResidentialAFSensitivity"
TagName = "TFM_INS"
DataLocation = "data_raw/coded_assumptions/sensitivities/af_testing/reset_afa_default.csv"





