# This file contains revisions we might make to the EEUD if the data is out of date
# (ie MBIE revisions have been made etc) and the main EEUD data doesn't reflect these yet

# Note: this is not a good long-term solution. Ideally we would used revised EEUD to align with official reporting.

# It's designed to modify everything within a group to match a new total, because we only have totals 

# The downstream script will identify all uses within a category as listed then scale up/down based on the existing results
# and the new value 

# Note: must represent values as TJs

[[revision]]
# update noted at Dec24 electricity tables release, likely from enz2025
# note: using estimated sales
Sector = "Residential"
Year = 2023
Fuel = "Electricity"
Total =  49_497.43


[[revision]]
# update noted at Dec24 electricity tables release, likely from enz2025
# note: using estimated sales
SectorGroup = "Commercial"
Year = 2023
Fuel = "Electricity"
Total =  34_009.00


