# Base year primary energy supply for TIMES:

# Gas 
# Oil 
# Coal
# Other Later probably (renewables) 

WorkBookName = "VT_TIMESNZ_PRI"

###########################################
# Gas
###########################################


[GasSupplyCommodityDefinitions]
Description = "Declare natural gas and fugitive emissions commodities (North Island only). Hardcoded in user config."
SheetName = "Natural Gas"
TagName = "FI_Comm"
Csets = ["NRG", "ENV"]
Region = ["NI", "NI"]
CommName = ["NGA", "GASCO2"]
Unit = ["PJ", "kt"]

[GasSupplyProcessDefinitions]
Description = "Declare natural gas production processes"
SheetName = "Natural Gas"
TagName = "FI_Process"
Sets = ["MIN", "MIN"] # this actually doesn't need to dupe - rows inherit so "MIN" would also be fine
TechName = ["MINNGA-KAP", "MINNGA-OTH"] # All other fields and Kapuni
Tact = ["PJ","PJ"]
Tcap = ["PJa","PJa"]
Region = ["NI", "NI"]


[GasSupplyParameters]
Description = "Production costs and fugitive emissions for domestic gas fields, and output commodity declaration."
SheetName = "Natural Gas"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_pri/natural_gas_production_parameters.csv"


[GasSupplyHistorical]
Description = "Hardcoded gas production limits for fields according to historical net outputs. Should code this from historical."
# copy-pasted from MBIE sheets. Could do a better job of this. subtracted kapuni from totals
SheetName = "Natural Gas"
TagName = "FI_T"
Attribute = ["ACT_BND~FX","ACT_BND~FX","ACT_BND~FX","ACT_BND~FX"]
TechName = ["MINNGA-KAP","MINNGA-KAP", "MINNGA-OTH","MINNGA-OTH"]
Year = [2023,2024,2023,2024]
NI = [12.11,14.24, 135.94, 104.73]


[GasSupplyForecasts]
Description = "Add natural gas production forecast limits. Excludes contingent - only the 2P reserves."
# Note contingent reserves are specified as a separate/optional scenario table
SheetName = "Natural Gas"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_pri/deliverability_forecasts_2p.csv"



# Distribution network 


[GasDistributionCommodities]
Description = "Defines distributed gas commodities"
# Note contingent reserves are specified as a separate/optional scenario table
SheetName = "Gas Distribution"
TagName = "FI_Comm"
CSets = ["NRG", "NRG"]
CommName = ["NGADD", "BIMDD"]
Unit = ["PJ", "PJ"]
LimType = ["FX", "FX"]


[GasDistributionNetworkDeclaration]
Description = "Defines gas distribution network"
# Note contingent reserves are specified as a separate/optional scenario table
SheetName = "Gas Distribution"
TagName = "FI_Process"
Sets = "PRE"
TechName = "G_NGA_DIST"
Tact = "PJ"
Tcap = "Pja"


[GasDistributionNetworkParameters]
Description = "Defines gas distribution network"
# Note contingent reserves are specified as a separate/optional scenario table
SheetName = "Gas Distribution"
TagName = "FI_Process"
Sets = "PRE"
TechName = "G_NGA_DIST"
Region = "NI"
NCAP_PASTI = 150 # this doesn't really matter - just enough to meet demand
CAP2ACT = 1 # just PJa capacity 
FIXOM = 200 # placeholder value. To determine correctly later. Note only important for objective function unless we're allowing the network to shrink.
Life = 100
[GasDistributionNetworkTopology]


Description = "Defines In/Out for network. Note that flo_eff must be set in base constraints or this will turn gas into biomethane for free"
# Note contingent reserves are specified as a separate/optional scenario table
SheetName = "Gas Distribution"
TagName = "FI_T"

TechName = ["G_NGA_DIST", "G_NGA_DIST"]
Comm-IN = ["NGA", "BIM"] # natural gas or biomethane. Note must add new fuels here and base constraints for additional blending 
Comm-OUT = ["NGADD", "BIMDD"] 
Ceff = [1,1] # might not need this? but had weird results without it in early testing where input commodities weren't needed. test removing.
Region = ["NI", "NI"]

           

###########################################
# Oil
###########################################

[OilSupplyCommodityDefinitions]
Description = "Define Oil and oil product commodities"
SheetName = "Oil"
TagName = "FI_Comm"
Csets = ["NRG"] # (all energy commodities) 
CommName = ["OILI",
            "LPG",
            "PET",
            "PET",
            "DSL",
            "FOL",
            "JET",]
Unit = ["PJ"] # All PJ 

[OilProcessDeclarations]
Description = "Declare oil and oil product supply processes (mining, imports). Include exports"
SheetName = "Oil"
TagName = "FI_Process"
DataLocation = "data_raw/coded_assumptions/oil_and_gas/oil_process_definitions.csv"

[OilSupplyProcessParameters]

Description = "Set base year activity and cost assumptions for oil product imports. Note extremely simple imports used directly"
SheetName = "Oil"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_pri/imported_fuel_costs.csv"


###########################################
# Coal
###########################################

# declaring that coal exists - very minimal input here 


[CoalCommodityDeclarations]
Description = "Declare coal commodity"
SheetName = "Coal"
TagName = "FI_Comm"
Csets = ["NRG"] # (all energy commodities) 
CommName = ["COA"]
Unit = ["PJ"] # All PJ 

[CoalProcessDeclarations]
Description = "Declare coal processes (mining and importing)"
SheetName = "Coal"
TagName = "FI_Process"
Sets = ["MIN", "IMP"] 
TechName = ["MINCOA", "IMPCOA"]
Tact = "PJ"
Tcap = "PJa"

[CoalParameterDeclarations]

Description = "Declare coal processes (mining and importing). Sets coal price (sans carbon) and annual availability . Very simple approach"
SheetName = "Coal"
TagName = "FI_T"
TechName = ["MINCOA", "IMPCOA"]
Comm-Out = ["COA", "COA"]
Cost = [7,7]
ACT_BND = [25,15] # not sure if this is necessary. Not very precise. Roughly equivalent to values in TIMES 2.0. 



###########################################
# TotalCO2
###########################################

[TOTCO2CommodityDefinition]

Description = "Declares TOTCO2 commodity. In old TIMES, all other emissions were re-declared here (not necessary)"
SheetName = "Total CO2"
TagName = "FI_Comm"
Csets = "ENV"
CommName = "TOTCO2"
Unit = "kt"

[TOTCO2AggregationDefinition]

Description = "Defines TOTCO2 as the sum of all other emissions commodities. No refinery."
SheetName = "Total CO2"
TagName = "COMAGG"
CommName = "TOTCO2"
ELCCO2 = 1
TRACO2 = 1
RESCO2 = 1
INDCO2 = 1
COMCO2 = 1
AGRCO2 = 1
GASCO2 = 1


###########################################
# Bio energy 
###########################################


# Declaring biofuels - these are fake entries and we can tidy up later when biomass module done 

[DeclareBiofuels]
Description = "Declare biofuel energy commodities"
SheetName = "Biofuels"
TagName = "FI_Comm"
Csets = ["NRG"] # (all energy commodities) 
CommName = ["WODWST", "AGRWST", "MNCWST", "ANMMNR", "WOD", "OSWOD", "BPLT", "BDSL", "BIL", "DID", "DIJ", "SAF", "BIG", "BIM"]
Unit = ["PJ"] # All PJ


[BiofuelProcessDeclarations]
Description = "Declare biomass/biofuel processes, including raw production and transformation"
SheetName = "Biofuels"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_pri/biofuel_supply_process_declarations.csv"

[BiofuelSupplyForecasts]
Description = "Biomass/biofuel supply and costs forecasts per region "
SheetName = "Biofuels"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_pri/biofuel_supply_forecasts.csv"

[BiofuelParameterDeclarations]
Description = "Declare conversion processes for biofuel. Sets investment and operation costs, annual availability, lifetime"
SheetName = "Biofuels"
TagName = "FI_T"
DataLocation = "data_raw/coded_assumptions/biofuels/plant_processes.csv"




