"""
This module takes the metadata file generated by reading tomls

And automatically outputs markdown documentation

NOTE: this method currently WIP.
need to reevaluate what would actually be useful when integrating with rtd method.
Have excluded from main workflow
"""

from pathlib import Path

import numpy as np
import pandas as pd
from prepare_times_nz.utilities.filepaths import PREP_LOCATION, STAGE_0_DATA

# CONSTANTS


input_file = STAGE_0_DATA / "config_metadata.csv"
OUTPUT_LOCATION = PREP_LOCATION / "docs/source/developer_guide/model_structure_docs"


def create_workbook_categories(df):
    """
    Expands the metadata csv to categorise each workbook

    Uses a dict of workbook prefixes and relevant labels

    That dict currently stored in this function, could move elsewhere
    """

    workbook_categories = {
        # Manual categorising of workbook names, based on address prefixes
        "SysSettings": "Settings",
        "VT_": "Base year (Historical) data",
        "BY_Trans": "Base year (Historical) data",
        "SuppXLS/Scen_": "Standard scenario",
        "SuppXLS/Demands": "Demand scenario",
        "SuppXLS/Trades/ScenTrade_": "Inter-regional trade",
        "SubRES_TMPL/SubRES_": "SubRES: Optional expansion of Reference Energy System",
    }

    # set default category. We also order these by their order in the input dict
    df["Category"] = "Other"
    df["Order"] = 10
    n = 0
    for prefix, category in workbook_categories.items():
        # otherwise map category based on workbook name. Room to expand these
        # Should go from less -> more detailed if clash,
        # as each subsequent entry will overwrite previous if applicable
        df["Category"] = np.where(
            df["WorkBookName"].str.startswith(prefix), category, df["Category"]
        )
        df["Order"] = np.where(
            df["WorkBookName"].str.startswith(prefix), n, df["Order"]
        )
        n += 1

    # sort by category, and alphabetically by workbookname within each category
    df = df.sort_values(["Order", "WorkBookName"])

    return df


# pylint: disable =  too-many-locals
def generate_tag_markdown(df):
    """

    Generates all our markdown.

    Should probably split this function up a bit

    """

    index_filename = "model-structure.md"

    index_text = []

    categories = df["Category"].unique().tolist()

    # Some header text for the main document
    index_text.append("# Output file structure")
    index_text.append("\n")
    index_text.append(
        "This document describes every input for the TIMES-NZ model structure and topology."
    )
    index_text.append(
        "All model inputs are contained in excel files generated by `PREPARE-TIMES-NZ`, "
    )
    index_text.append(
        "and this documentation is automatically generated whenever there is an update."
    )
    index_text.append(
        "It is intended to guide developers and users to better understand all TIMES-NZ input data."
    )
    index_text.append("\n")

    index_text.append("Documents are organised by broad category.")

    index_text.append("```{toctree}")
    index_text.append(":maxdepth: 2")
    index_text.append(":caption: Files")

    for category in categories:

        # create a folder for this category
        category_dir = Path(OUTPUT_LOCATION / category)
        category_dir.mkdir(parents=True, exist_ok=True)

        # category_index_filename = category_dir / "index.md"

        # create an index file in the category folder
        category_index_text = []
        category_index_text.append(f"# {category}")
        category_index_text.append("\n")
        category_index_text.append("```{toctree}")
        category_index_text.append(":maxdepth: 2")
        category_index_text.append(":caption: Files")

        df_c = df[df["Category"] == category]
        workbooks = df_c["WorkBookName"].unique().tolist()

        for w in workbooks:

            # add this workbook to the category index toctree

            category_index_text.append(category)

            # data
            df_w = df_c[df_c["WorkBookName"] == w]

            # filename for this markdown file
            filename = f"{w}.md"
            filename = filename.replace("/", "_")

            # get output locations for this

            workbook_text = []

            workbook_text.append(f"## {w}.xlsx")

            sheets = df_w["SheetName"].unique().tolist()

            for s in sheets:
                df_s = df_w[df_w["SheetName"] == s]

                workbook_text.append(f"### WorkSheet: {s}")

                tables = df_s["TableName"].unique().tolist()

                for t in tables:
                    df_t = df_s[df_s["TableName"] == t]

                    workbook_text.append(f"**{t}**: ")
                    workbook_text.append(f"{df_t["Description"].unique()[0]}")
                    workbook_text.append("\n")
                    workbook_text.append(
                        f" - Veda Tag: `{df_t["VedaTag"].unique()[0]}`"
                    )
                    workbook_text.append("\n")
                    workbook_text.append(
                        f" - Data Location: `{df_t["DataLocation"].unique()[0]}`"
                    )
                    workbook_text.append("\n")

            workbook_text = "\n".join(workbook_text)
            (category_dir / filename).write_text(workbook_text, encoding="utf-8")

    index_text.append("```")
    index_text = "\n".join(index_text)
    index_path = OUTPUT_LOCATION.parent / index_filename

    index_path.write_text(index_text, encoding="utf-8")


def main():
    """entry point"""

    OUTPUT_LOCATION.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(input_file)
    df = create_workbook_categories(df)
    generate_tag_markdown(df)


if __name__ == "__main__":
    main()
