# This file configures the technologies where we add additional constraints on uptake 

# Each constraint is represented as a CAP GROWTH user constraint

# Required entries: 

# Description: Some plain english description of what's going on 
# Growth Limit: the % increase capacity can grow by 
# Pset_[Set|PN|CI|CO] Process sets, names, commodities in, or commodities out. wildcards possible, any combination is possible


# Possible Entries: 

# SeedValue: Optional additional capacity which can be installed above the % limit.
#    (Necessary if capacity is 0 to start with before growth becomes dynamic.)
# StartYear - a year for the constraint to activate from. Note default to baseyear.



# Residential

[CapLimitResidentialLED]
Description = "Residential LED lighting can only grow at 4% annually"
GrowthLimit = 0.04
PSet_PN = "RES*LED-LIGHT" 

[CapLimitResidentialFluro]
Description = "Residential Fluro lighting can only grow at 1% annually"
GrowthLimit = 0.01 
PSet_PN = "RES*FLUOR-LIGHT" 

[CapLimitResidentialHeatPumps]
Description = "Residential HP capacity can only grow at 3% annually"
GrowthLimit = 0.03
PSet_PN = "RES*HPSH-S_HEAT"

[CapLimitResLPGHeating]
Description = "Residential LPG space heating can only grow 2% annually"
GrowthLimit = 0.02
PSet_PN = "RES*LPG-BURNR-S_HEAT"

[CapLimitResGasHeating]
Description = "Residential NGA space heating can only grow 2% annually"
GrowthLimit = 0.02
PSet_PN = "RES*NGA-BURNR-S_HEAT"

[CapLimitResLPGHotwater]
Description = "Residential LPG water heating can only grow 2% annually"
GrowthLimit = 0.02
PSet_PN = "RES*LPG*WH_LOW"

[CapLimitResGasHotwater]
Description = "Residential NGA water heating can only grow 2% annually"
GrowthLimit = 0.02
PSet_PN = "RES*NGA*WH_LOW"

# INDUSTRY 
[CapLimitDairyHeatpumps]
Description = "Dairy processing heatpump installs limited to 1% + 50MW annually"
GrowthLimit = 0.01
SeedValue = 0.05
PSet_PN = "DARY-ELC-HPPH-PH_LOW"

[CapLimitIndustryHeatpumps]
Description = "Industrial space heating heat pumps limited to total 5MW annually"
GrowthLimit = 0.01
SeedValue = 0.005
PSet_PN = "*HPSH-SH_LOW"

# TRANSPORT

[CapLimitPassengerBEV]
Description = "Very generous limit on LPV uptake rates, just to slow any really crazy early swings. 50% annual max cap increase"
GrowthLimit = 0.5
PSet_PN = "T_*_CBEVELC_*"

# COMMERCIAL

[CapLimitCommercialLED]
Description = "Commercial LED lighting can only grow at 4% annually (except datacentres)"
GrowthLimit = 0.04
PSet_PN = "C_*LT-LED-ELC, -C_DATA-LT-LED-ELC" 

[CapLimitCommercialFluro]
Description = "Commercial Fluro lighting can only grow at 1% annually"
GrowthLimit = 0.01 
PSet_PN = "C_*LT-FLU-ELC" 

[CapLimitCommercialCooktopsELC]
Description = "Commercial electric cooktops can only grow at 4% annually"
GrowthLimit = 0.04
PSet_PN = "C_WSR-CK-CK-ELC"
# 
[CapLimitCommercialOvensELC]
Description = "Commercial electric ovens can only grow at 4% annually"
GrowthLimit = 0.02
PSet_PN = "C_WSR-CK-Ovens-ELC"
# 
[CapLimitCommercialOvensLPG]
Description = "Commercial LPG ovens can only grow at 2% annually"
GrowthLimit = 0.02
PSet_PN = "C_WSR-CK-Ovens-LPG"

[CapLimitCommercialOvensNGA]
Description = "Commercial NGA ovens can only grow at 2% annually"
GrowthLimit = 0.02
PSet_PN = "C_WSR-CK-Ovens-NGA"


[CapLimitBIGAD]
Description = "Limits on AD capacity growth rates - can only build so mmuch at once. Generous, just not allowing huge spikes"
GrowthLimit = 0.3
PSet_PN = "REF_ANDGST"


