name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout times-excel-reader
      uses: actions/checkout@v2
      with:
        repository: etsap-TIMES/times-excel-reader
        path: tool

    - name: Checkout TIMES-NZ-Model-Files
      uses: actions/checkout@v2
      with:
        repository: EECA-NZ/TIMES-NZ-Model-Files
        path: model
        token: ${{ secrets.GH_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd tool
        pip install -r requirements.txt

    - name: Run raw_table_summary on TIMES-NZ-Model-Files
      run: |
        cd model/utils
        python raw_table_summary.py

    - name: Display output
      run: |
        cd model/TIMES-NZ/raw_table_summary
        cat raw_tables.txt

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: TIMES-NZ/raw_table_summary/raw_tables.txt

    - name: Run times-excel-reader on TIMES-NZ-Model-Files
      run: |
        cd tool
        # python times_excel_reader.py ../model # CURRENTLY BROKEN