# This config file is used to generate new industrial technologies and define what existing uses/techs they might replace

[newtechsSGHP]
TechCode = "SGHP"
Technology = "Steam Generating Heat Pump"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["PH_INT", "PH_LOW"] # intermediate/low process heat
ReplacedTechs = ["BOILR"] # just boiler use (could expand to furnace/kiln possibly?)
InputFuel = ["ELC"]
Sectors = ["DARY", "MEAT", "WOOD", "PULP", "OTHR", "FOOD"]

[newtechsBOILR]
TechCode = "BOILR" # NOTE: existing tech code. Below labels match concordances for BOILR in industrial use
Technology = "Boiler Systems"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["PH_LOW"] # process heating boiler
ReplacedTechs = ["BOILR"] # replacing other boilers (nga, coal, etc - anything not electricity)
InputFuel = ["ELC"]
Sectors = ["DARY", "MEAT", "OTHR", "FOOD", "MINE"]

[newtechsEFURNC]
TechCode = "EFURNC" # NOTE: Existing tech code. 
# similar to boilers, this is just about expanding the use to sectors that don't currently have access
# allows all sectors to electrify high temp process heat (at high cost obviously) 
# if we just stick with BY methods, some are limited to nga/fuel oil with no other options 
Technology = "Electric Furnace"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["PH_HIGH"] # high temp PH 
ReplacedTechs = ["FURNC", "BOILR"] # any furnace or boiler use can use this instead
InputFuel = ["ELC"]
Sectors = ["PULP", "CHEM", "STEEL"] # other sectors have methods already or dont use high temp

[newtechsHPPH]
TechCode = "HPPH"
Technology = "Heat Pump (process heat)"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["PH_LOW"] # low process heat
ReplacedTechs = ["BOILR", "BURNR", "FURNC"]
InputFuel = ["ELC"]
Sectors = ["DARY", "FOOD", "MEAT", "MNRL", "OTHR", "PULP", "STEEL"]

[newtechsHPSH]
TechCode = "HPSH"
Technology = "Heat Pump (space heating)"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["SH_LOW"] # low process heat
InputFuel = ["ELC"]
# all sectors except CHEM (which has the tech already from the EEUD)
Sectors = ["ALUM","CNST","DARY","FOOD","STEEL","MEAT","METH","MINE","MNRL","OTHR","PULP","UREA","WOOD"]

[newtechsBIOFURNC]
TechCode = "BIOFURNC"
Technology = "Furnace/Kiln"
TechnologyGroup = "Heat/Cooling Devices"
EndUse = ["PH_HIGH"]
ReplacedTechs = ["FURNC"]
InputFuel = ["WOD"]
Sectors = ["MNRL"]

[newtechsBEV]
TechCode = "BEV"
Technology = "Electric Vehicle"
TechnologyGroup = "Mobile Motors"
EndUse = ["MTV_MOB"] 
ReplacedTechs = ["ICENG"]
InputFuel = ["ELC"]
Sectors = ["CNST", "OTHR", "MINE"]
 
[newtechsHFCV]
TechCode = "HFCV"
Technology = "Hydrogen Vehicle"
TechnologyGroup = "Mobile Motors"
EndUse = ["MTV_MOB"] 
ReplacedTechs = ["ICENG"]
InputFuel = ["H2R"]
Sectors = ["CNST", "OTHR", "MINE"]
